logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
server:
  port: 8081
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      discovery:
        register: false
        registerHealthCheck: false
      config:
        enabled: false
      host: localhost
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: persons
          uri: lb://persons-service
          predicates:
            - Path=/persons/**
          filters:
            - RewritePath=/persons/(?<path>.*), /actuator/health/$\{path}
#        - id: auth
#          uri: http://localhost:9100
#          predicates:
#            - Path=/auth/**
#            - Method=POST
#          filters:
#            - RewritePath=/auth/(?<path>.*), /auth/$\{path}
