logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      discovery:
        register: false
        registerHealthCheck: false
      config:
        enabled: false
      host: localhost
    gateway:
      default-filters:
      #Remove All the sensitive request headers (Cookie, Set-Cookie & Authorization) while passing request to downstream services
#        - RemoveRequestHeader=Cookie
#        - RemoveRequestHeader=Set-Cookie
#        - RemoveRequestHeader=Authorization
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication
          uri: http://fungover.org
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /api/docs/$\{path}
